### ISSUE TITLE
Support for Winston 3

### ISSUE THREAD

**Issue by tmazyrko** [debarghyab/rabbitmq-logger#330]
Attempting to use this module with the latest version of Winston (3.3.3) results in the following error:

```
name is a legacy winston transport. Consider upgrading:
- Upgrade docs: https://github.com/winstonjs/winston/blob/master/UPGRADE-3.0.md
```

Any possibility to get this module updated? Winston 3.0 breaking changes and upgrade docs are found [here](https://github.com/winstonjs/winston/blob/master/UPGRADE-3.0.md#transports).

**Comment by tmazyrko** [comment]
This is the rest of the error after the legacy module warning:

```
Error: [RabbitmqTransport]: Cannot read property 'publish' of undefined
    at RabbitmqTransport.log (C:\Users\Tim\WebstormProjects\BossBattles-server\node_modules\rabbitmq-logger\src\RabbitmqTransport.js:176:19)
    at LegacyTransportStream._write (C:\Users\Tim\WebstormProjects\BossBattles-server\node_modules\winston-transport\legacy.js:62:20)
    at doWrite (C:\Users\Tim\WebstormProjects\BossBattles-server\node_modules\winston-transport\node_modules\readable-stream\lib\_stream_writable.js:428:64)
    at writeOrBuffer (C:\Users\Tim\WebstormProjects\BossBattles-server\node_modules\winston-transport\node_modules\readable-stream\lib\_stream_writable.js:417:5)
    at LegacyTransportStream.Writable.write (C:\Users\Tim\WebstormProjects\BossBattles-server\node_modules\winston-transport\node_modules\readable-stream\lib\_stream_writable.js:334:11)
    at DerivedLogger.ondata (C:\Users\Tim\WebstormProjects\BossBattles-server\node_modules\readable-stream\lib\_stream_readable.js:681:20)
    at DerivedLogger.emit (events.js:400:28)
    at addChunk (C:\Users\Tim\WebstormProjects\BossBattles-server\node_modules\readable-stream\lib\_stream_readable.js:298:12)
    at readableAddChunk (C:\Users\Tim\WebstormProjects\BossBattles-server\node_modules\readable-stream\lib\_stream_readable.js:280:11)
    at DerivedLogger.Readable.push (C:\Users\Tim\WebstormProjects\BossBattles-server\node_modules\readable-stream\lib\_stream_readable.js:241:10)
    at DerivedLogger.Transform.push (C:\Users\Tim\WebstormProjects\BossBattles-server\node_modules\readable-stream\lib\_stream_transform.js:139:32)
    at DerivedLogger._transform (C:\Users\Tim\WebstormProjects\BossBattles-server\node_modules\winston\lib\winston\logger.js:305:12)
    at DerivedLogger.Transform._read (C:\Users\Tim\WebstormProjects\BossBattles-server\node_modules\readable-stream\lib\_stream_transform.js:177:10)
    at DerivedLogger.Transform._write (C:\Users\Tim\WebstormProjects\BossBattles-server\node_modules\readable-stream\lib\_stream_transform.js:164:83)
    at doWrite (C:\Users\Tim\WebstormProjects\BossBattles-server\node_modules\readable-stream\lib\_stream_writable.js:409:139)
    at writeOrBuffer (C:\Users\Tim\WebstormProjects\BossBattles-server\node_modules\readable-stream\lib\_stream_writable.js:398:5)

```
